### ISSUE TITLE
Heartbeats stuck at 0%?

### ISSUE THREAD

**Issue by lube** [geremih/PogoMap#5]
Like the tittle says I cannot get through the 4th step on scan heartbeats

**Comment by geremih** [comment]
Niantic has stopped acknowledging requests that don't have a well-formed unknown6 field. I'm not working on the project at the moment, so youll have  to implement that part if you want too use it. Niantic might have made other changes to the API too, you should check if a reference implementation to be sure.

**Comment by lube** [comment]
I already found a way to mock it, I wasnt really interested in the hearthbeat functionality anw.

Thanks very much, your project has helped me to understand react-native a ton!

**Comment by geremih** [comment]
Awesome. Glad to know it helped!
